# Generated by Django 3.2.12 on 2022-04-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fuelquotemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelquotemodel',
            name='profile',
        ),
    ]
